#!/usr/bin/python3
from sys import argv
from math import sqrt


def factor():
    with open(argv[1]) as factr:
        for inp in factr:
            num = int(inp)
            print("{:d}=".format(num), end="")
            if num % 2 == 0:
                print("{}*2".format(num//2))
                continue
            sqn = int(sqrt(num))
            if sqn % 2 == 0:
                sqn += 1
            for a in range(3, sqn + 1, 2):
                if num % a == 0:
                    print("{}*{}".format(a, num//a))
                    break
            if num % a != 0:
                print("{}={}*1".format(num, num))


factor()
